### ISSUE TITLE
Test failure around test_password_* on 1.1.0-alpha.10

### ISSUE THREAD

**Issue by mweinelt** [kanidm/kanidm#1170]
### I did this

Updated the package for nixpkgs and ran the test suite.

### I expected the following

The test suite should succeed

### Kanidm version (and git commit)

v1.1.0-alpha.10

### Operating System / Version

NixOS unstable (5.19.17)
OpenSSL 3.0.7

### Any other comments

```
kanidm> failures:
kanidm> 
kanidm> ---- credential::tests::test_password_from_samba_nt_hash stdout ----
kanidm> thread 'credential::tests::test_password_from_samba_nt_hash' panicked at 'assertion failed: r.verify(password).unwrap_or(false)', kanidmd/lib/src/credential/mod.rs:1216:9
kanidm> stack backtrace:
kanidm>    0:     0x5555561247e3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2ea00d5f3b53d9f
kanidm>    1:     0x5555556f70fe - core::fmt::write::ha076a7e65c6b1874
kanidm>    2:     0x555556138925 - std::io::Write::write_fmt::h64b8a4975d0de54e
kanidm>    3:     0x555556140bba - std::panicking::default_hook::{{closure}}::h64163197f96398c1
kanidm>    4:     0x555556140834 - std::panicking::default_hook::h92625161492e6b48
kanidm>    5:     0x555556141146 - std::panicking::rust_panic_with_hook::hfdd7d6bb6788c6c2
kanidm>    6:     0x555556124acc - std::panicking::begin_panic_handler::{{closure}}::he81a60a7ef84ad4a
kanidm>    7:     0x555556124904 - std::sys_common::backtrace::__rust_end_short_backtrace::h62801bf9780239e6
kanidm>    8:     0x555556140e4d - rust_begin_unwind
kanidm>    9:     0x555555661ba3 - core::panicking::panic_fmt::hfd221b9f37504b4a
kanidm>   10:     0x555555661a6d - core::panicking::panic::hd81cbc87c8887358
kanidm>   11:     0x555555c42435 - kanidmd_lib::credential::tests::test_password_from_samba_nt_hash::hbfdf58f5bd6f1923
kanidm>                                at /build/source/kanidmd/lib/src/credential/mod.rs:1216:9
kanidm>   12:     0x555556183553 - test::__rust_begin_short_backtrace::h9b2e77c47cf6ee50
kanidm>   13:     0x555556183682 - test::run_test_in_process::h79412f4edc07b6d4
kanidm>   14:     0x55555616809e - std::sys_common::backtrace::__rust_begin_short_backtrace::h54ced9bc69974c9a
kanidm>   15:     0x55555616ace8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ce6207c2f1d1339
kanidm>   16:     0x555556139405 - std::sys::unix::thread::Thread::new::thread_start::h1f2eb64c3e9233cd
kanidm>   17:     0x7ffff77dde86 - start_thread
kanidm>   18:     0x7ffff7864c60 - __clone3
kanidm>   19:                0x0 - <unknown>
kanidm> 
kanidm> ---- credential::tests::test_password_from_ipa_nt_hash stdout ----
kanidm> thread 'credential::tests::test_password_from_ipa_nt_hash' panicked at 'assertion failed: r.verify(password).unwrap_or(false)', kanidmd/lib/src/credential/mod.rs:1206:9
kanidm> stack backtrace:
kanidm>    0:     0x5555561247e3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2ea00d5f3b53d9f
kanidm>    1:     0x5555556f70fe - core::fmt::write::ha076a7e65c6b1874
kanidm>    2:     0x555556138925 - std::io::Write::write_fmt::h64b8a4975d0de54e
kanidm>    3:     0x555556140bba - std::panicking::default_hook::{{closure}}::h64163197f96398c1
kanidm>    4:     0x555556140834 - std::panicking::default_hook::h92625161492e6b48
kanidm>    5:     0x555556141146 - std::panicking::rust_panic_with_hook::hfdd7d6bb6788c6c2
kanidm>    6:     0x555556124acc - std::panicking::begin_panic_handler::{{closure}}::he81a60a7ef84ad4a
kanidm>    7:     0x555556124904 - std::sys_common::backtrace::__rust_end_short_backtrace::h62801bf9780239e6
kanidm>    8:     0x555556140e4d - rust_begin_unwind
kanidm>    9:     0x555555661ba3 - core::panicking::panic_fmt::hfd221b9f37504b4a
kanidm>   10:     0x555555661a6d - core::panicking::panic::hd81cbc87c8887358
kanidm>   11:     0x555555c42255 - kanidmd_lib::credential::tests::test_password_from_ipa_nt_hash::hfe4d37aabdbdedd2
kanidm>                                at /build/source/kanidmd/lib/src/credential/mod.rs:1206:9
kanidm>   12:     0x555556183553 - test::__rust_begin_short_backtrace::h9b2e77c47cf6ee50
kanidm>   13:     0x555556183682 - test::run_test_in_process::h79412f4edc07b6d4
kanidm>   14:     0x55555616809e - std::sys_common::backtrace::__rust_begin_short_backtrace::h54ced9bc69974c9a
kanidm>   15:     0x55555616ace8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ce6207c2f1d1339
kanidm>   16:     0x555556139405 - std::sys::unix::thread::Thread::new::thread_start::h1f2eb64c3e9233cd
kanidm>   17:     0x7ffff77dde86 - start_thread
kanidm>   18:     0x7ffff7864c60 - __clone3
kanidm>   19:                0x0 - <unknown>
kanidm> 
kanidm> 
kanidm> failures:
kanidm>     credential::tests::test_password_from_ipa_nt_hash
kanidm>     credential::tests::test_password_from_samba_nt_hash
kanidm> 
kanidm> test result: FAILED. 287 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.52s

**Comment by Firstyear** [comment]
Ahhhh we've seen this before. I think this is because openssl *may* be shipped without md4 support? 

Can you try the tests with:

```
RUST_LOG=trace cargo test test_password_from_ipa_nt_hash
```

And at the end of the test look for a line like: "Unable to access MD4 - fips mode enabled?". That would indicate that MD4 isn't built/available in your openssl provider, which would cause this.

This is NOT a blocker for run time though, since the error *is* handled correctly at runtime, returning a valid and correct error that we can't import the md4 hash. It's just that the test suite currently assumes that it will always be present.

So I think a *possible* way to resolve could be to make the test suite more robust to check if MD4 is available before running the test.

**Comment by Firstyear** [comment]
From https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers it may be that the legacy provider is disabled or not installed.

**Comment by mweinelt** [comment]
```
kanidm> running 1 test
kanidm> test credential::tests::test_password_from_ipa_nt_hash ... FAILED
kanidm> 
kanidm> failures:
kanidm> 
kanidm> ---- credential::tests::test_password_from_ipa_nt_hash stdout ----
kanidm> thread 'credential::tests::test_password_from_ipa_nt_hash' panicked at 'assertion failed: r.verify(password).unwrap_or(false)', kanidmd/lib/src/credential/mod.rs:1206:9
kanidm> stack backtrace:
kanidm>    0:     0x555557b0e73c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2ea00d5f3b53d9f
kanidm>    1:     0x555557b45ace - core::fmt::write::ha076a7e65c6b1874
kanidm>    2:     0x555557b22711 - std::io::Write::write_fmt::h64b8a4975d0de54e
kanidm>    3:     0x555557b2aca5 - std::panicking::default_hook::{{closure}}::h64163197f96398c1
kanidm>    4:     0x555557b2a941 - std::panicking::default_hook::h92625161492e6b48
kanidm>    5:     0x555557b2b1c1 - std::panicking::rust_panic_with_hook::hfdd7d6bb6788c6c2
kanidm>    6:     0x555557b0ea39 - std::panicking::begin_panic_handler::{{closure}}::he81a60a7ef84ad4a
kanidm>    7:     0x555557b0e854 - std::sys_common::backtrace::__rust_end_short_backtrace::h62801bf9780239e6
kanidm>    8:     0x555557b2ae72 - rust_begin_unwind
kanidm>    9:     0x5555557809a3 - core::panicking::panic_fmt::hfd221b9f37504b4a
kanidm>   10:     0x55555578086d - core::panicking::panic::hd81cbc87c8887358
kanidm>   11:     0x555555dee8cb - kanidmd_lib::credential::tests::test_password_from_ipa_nt_hash::h1151043a20a04bf5
kanidm>                                at /build/source/kanidmd/lib/src/credential/mod.rs:1206:9
kanidm>   12:     0x555555dee77a - kanidmd_lib::credential::tests::test_password_from_ipa_nt_hash::{{closure}}::h48192b04b85f6194
kanidm>                                at /build/source/kanidmd/lib/src/credential/mod.rs:1200:5
kanidm>   13:     0x5555566c8aee - core::ops::function::FnOnce::call_once::h41518555b8b594be
kanidm>                                at /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
kanidm>   14:     0x5555570dcf43 - test::__rust_begin_short_backtrace::h9b2e77c47cf6ee50
kanidm>   15:     0x5555570dd0ad - test::run_test_in_process::h79412f4edc07b6d4
kanidm>   16:     0x5555570ff514 - std::sys_common::backtrace::__rust_begin_short_backtrace::h54ced9bc69974c9a
kanidm>   17:     0x555557101c96 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ce6207c2f1d1339
kanidm>   18:     0x555557b231e3 - std::sys::unix::thread::Thread::new::thread_start::h1f2eb64c3e9233cd
kanidm>   19:     0x7ffff77dbe86 - start_thread
kanidm>   20:     0x7ffff7862c60 - __clone3
kanidm>   21:                0x0 - <unknown>
kanidm> 
kanidm> 
kanidm> failures:
kanidm>     credential::tests::test_password_from_ipa_nt_hash
kanidm> 
kanidm> test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 288 filtered out; finished in 0.33s
kanidm> 
kanidm> error: test failed, to rerun pass '-p kanidmd_lib --lib'
```

Doesn't look very tracey. Here is what I did to run this:

```diff
+  preCheck = ''
+    export RUST_BACKTRACE=full
+    export RUST_LOG=trace
+    echo "precheck test begin"
+    cargo test test_password_from_ipa_nt_hash
+    echo "precheck test end"
+    exit 1
+  '';
+
````

**Comment by Firstyear** [comment]
What distro/env are you using? I might be able to reproduce on my own.

**Comment by mweinelt** [comment]
I'm on NixOS. There are probably other distros where this can be reproduced easier.

**Comment by yaleman** [comment]
I'm having the same issue on macOS, rust v1.64.0 (stable)

```
❯ cargo test -p kanidmd_lib --lib test_password_
   Compiling getrandom v0.2.8
   Compiling sha2 v0.9.9
   Compiling chrono v0.4.22
   Compiling blake3 v0.3.8
   Compiling webauthn-rs-proto v0.4.7
   Compiling tokio v1.21.2
   Compiling rand_core v0.6.4
   Compiling ahash v0.7.6
   Compiling uuid v1.2.1
   Compiling fernet v0.2.0
   Compiling rand_chacha v0.3.1
   Compiling hashbrown v0.12.3
   Compiling compact_jwt v0.2.8
   Compiling rand v0.8.5
   Compiling kanidm_proto v1.1.0-alpha.11-dev (./kanidm/kanidm_proto)
   Compiling webauthn-authenticator-rs v0.4.7
   Compiling indexmap v1.9.1
   Compiling hashlink v0.8.1
   Compiling lru v0.7.8
   Compiling rusqlite v0.28.0
   Compiling cookie v0.14.4
   Compiling clap v3.2.23
   Compiling webauthn-rs-core v0.4.7
   Compiling async-global-executor v2.3.1
   Compiling tokio-util v0.7.4
   Compiling tracing-forest v0.1.4 (https://github.com/QnnOkabayashi/tracing-forest.git?rev=48d78f7294ceee47a22eee5c80964143c4fb3fe1#48d78f72)
   Compiling concread v0.4.0
   Compiling r2d2_sqlite v0.21.0
   Compiling async-std v1.12.0
   Compiling ldap3_proto v0.2.3
   Compiling webauthn-rs v0.4.7
   Compiling criterion v0.4.0
   Compiling http-types v2.12.0
   Compiling async-session v2.0.1
   Compiling async-h1 v2.3.3
   Compiling http-client v6.5.3
   Compiling async-sse v4.1.0
   Compiling tide v0.16.0
   Compiling sketching v1.1.0-alpha.11-dev (./kanidm/sketching)
   Compiling kanidmd_lib v1.1.0-alpha.11-dev (./kanidm/kanidmd/lib)
    Finished test [unoptimized + debuginfo] target(s) in 32.04s
     Running unittests src/lib.rs (target/debug/deps/kanidmd_lib-6a577f51af6d642f)

running 9 tests
test credential::tests::test_password_from_invalid ... ok
test credential::tests::test_password_from_ds_ssha512 ... ok
test credential::tests::test_password_from_openldap_pkbdf2_sha256 ... ok
test credential::tests::test_password_from_openldap_pkbdf2_sha1 ... ok
test credential::tests::test_password_from_openldap_pkbdf2 ... ok
test credential::tests::test_password_from_ipa_nt_hash ... FAILED
test credential::tests::test_password_from_samba_nt_hash ... FAILED
test credential::tests::test_password_from_openldap_pkbdf2_sha512 ... ok
test credential::tests::test_password_from_django_pbkdf2_sha256 ... ok

failures:

---- credential::tests::test_password_from_ipa_nt_hash stdout ----
thread 'credential::tests::test_password_from_ipa_nt_hash' panicked at 'assertion failed: r.verify(password).unwrap_or(false)', kanidmd/lib/src/credential/mod.rs:1206:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- credential::tests::test_password_from_samba_nt_hash stdout ----
thread 'credential::tests::test_password_from_samba_nt_hash' panicked at 'assertion failed: r.verify(password).unwrap_or(false)', kanidmd/lib/src/credential/mod.rs:1216:9


failures:
    credential::tests::test_password_from_ipa_nt_hash
    credential::tests::test_password_from_samba_nt_hash

test result: FAILED. 7 passed; 2 failed; 0 ignored; 0 measured; 280 filtered out; finished in 0.03s

error: test failed, to rerun pass '-p kanidmd_lib --lib'
```

**Comment by Firstyear** [comment]
@yaleman How did you install openssl? Brew? Or vendored in the package? 

brew search openssl :)

**Comment by Firstyear** [comment]
I can reproduce now, so I'll submit a fix shortly.

**Comment by yaleman** [comment]
```
❯ brew info openssl
==> openssl@3: stable 3.0.7 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/opt/homebrew/Cellar/openssl@3/3.0.7 (6,454 files, 28.0MB)
  Poured from bottle on 2022-11-03 at 17:27:28
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates ✔
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@3/certs

and run
  /opt/homebrew/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```
