### ISSUE TITLE
Permission denied error in RADIUS docker image

### ISSUE THREAD

**Issue by czzrr** [kanidm/kanidm#1438]
### I did this

```console
ca@ubu:~/kanidm$ make build/radiusd
ca@ubu:~/kanidm$ cd rlm_python && ./run_radius_container.sh
+ '[' -z '' ']'
+ IMAGE=kanidm/radius:devel
+ echo 'Running docker container: kanidm/radius:devel'
Running docker container: kanidm/radius:devel
+ '[' -z '' ']'
++ pwd
+ CONFIG_FILE=/home/ca/kanidm/rlm_python/../examples/kanidm
+ echo 'Using config file: /home/ca/kanidm/rlm_python/../examples/kanidm'
Using config file: /home/ca/kanidm/rlm_python/../examples/kanidm
+ '[' '!' -d /tmp/kanidm/ ']'
+ echo 'Starting the dev container...'
Starting the dev container...
+ docker run --rm -it --network host --name radiusd -v /tmp/kanidm/:/data/ -v /tmp/kanidm/:/tmp/kanidm/ -v /tmp/kanidm/:/certs/ -v /home/ca/kanidm/rlm_python/../examples/kanidm:/data/kanidm kanidm/radius:devel
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Copying /certs/ca.pem to /etc/raddb/certs/ca.pem
Traceback (most recent call last):
  File "/radius_entrypoint.py", line 166, in <module>
    setup_certs(kanidm_config)
  File "/radius_entrypoint.py", line 62, in setup_certs
    shutil.copyfile(cert_ca, CERT_CA_DEST)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/etc/raddb/certs/ca.pem'
```

Bypassing this error gives another permission error:
```console
ca@ubu:~/kanidm/rlm_python$ ./run_radius_container.sh 
+ '[' -z '' ']'
+ IMAGE=kanidm/radius:devel
+ echo 'Running docker container: kanidm/radius:devel'
Running docker container: kanidm/radius:devel
+ '[' -z '' ']'
++ pwd
+ CONFIG_FILE=/home/ca/kanidm/rlm_python/../examples/kanidm
+ echo 'Using config file: /home/ca/kanidm/rlm_python/../examples/kanidm'
Using config file: /home/ca/kanidm/rlm_python/../examples/kanidm
+ '[' '!' -d /tmp/kanidm/ ']'
+ echo 'Starting the dev container...'
Starting the dev container...
+ docker run --rm -it --network host --name radiusd -v /tmp/kanidm/:/data/ -v /tmp/kanidm/:/tmp/kanidm/ -v /tmp/kanidm/:/certs/ -v /home/ca/kanidm/rlm_python/../examples/kanidm:/data/kanidm kanidm/radius:devel
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Copying /certs/ca.pem to /etc/raddb/certs/ca.pem
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
rehash: warning: skipping duplicate certificate in server.pem
rehash: warning: skipping duplicate certificate in client.pem
rehash: warning: skipping duplicate certificate in user@example.org.pem
rehash: warning: skipping duplicate certificate in 01.pem
rehash: warning: skipping ca.crl,it does not contain exactly one certificate or CRL
rehash: warning: skipping duplicate certificate in 02.pem
Received SIGCHLD ...
Copying /certs/dh.pem to /etc/raddb/certs/dh.pem
Traceback (most recent call last):
  File "/radius_entrypoint.py", line 167, in <module>
    write_clients_conf(kanidm_config)
  File "/radius_entrypoint.py", line 42, in write_clients_conf
    with raddb_config_file.open('w', encoding='utf-8') as file_handle:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/etc/raddb/clients.conf'
```

Permissions in container:
```console
freerad@ubu:~$ ls /etc/raddb/certs -al
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
total 180
drwxrwsr-x 1 freerad freerad 4096 Feb 16 15:13 .
drwxr-s--x 1 freerad freerad 4096 Feb 16 15:13 ..
-rw-r--r-- 1 root    root    4889 Feb 16 15:13 01.pem
-rw-r--r-- 1 root    root    4739 Feb 16 15:13 02.pem
-rw-r--r-- 1 root    root    6465 Feb 16 15:12 Makefile
-rw-r--r-- 1 root    root    8289 Feb 16 15:12 README.md
-rwxr-xr-x 1 root    root    2798 Feb 16 15:12 bootstrap
-rw-r--r-- 1 root    root    1432 Feb 16 15:12 ca.cnf
-rw-r--r-- 1 root    root     478 Feb 16 15:13 ca.crl
-rw-r--r-- 1 root    root    1278 Feb 16 15:13 ca.der
-rw-r--r-- 1 root    root    1854 Feb 16 15:13 ca.key
-rw-r--r-- 1 root    root    1785 Feb 16 15:13 ca.pem
-rw-r--r-- 1 root    root    1103 Feb 16 15:12 client.cnf
-rw-r--r-- 1 root    root    4739 Feb 16 15:13 client.crt
-rw-r--r-- 1 root    root    1045 Feb 16 15:13 client.csr
-rw-r--r-- 1 root    root    1854 Feb 16 15:13 client.key
-rw-r--r-- 1 root    root    2787 Feb 16 15:13 client.p12
-rw-r--r-- 1 root    root    3794 Feb 16 15:13 client.pem
-rw-r--r-- 1 root    root     424 Feb 16 15:13 dh
-rw-r--r-- 1 root    root     229 Feb 16 15:13 index.txt
-rw-r--r-- 1 root    root      21 Feb 16 15:13 index.txt.attr
-rw-r--r-- 1 root    root      21 Feb 16 15:13 index.txt.attr.old
-rw-r--r-- 1 root    root     120 Feb 16 15:13 index.txt.old
-rw-r--r-- 1 root    root    1155 Feb 16 15:12 inner-server.cnf
-rw-r--r-- 1 root    root     166 Feb 16 15:13 passwords.mk
-rw-r--r-- 1 root    root       3 Feb 16 15:13 serial
-rw-r--r-- 1 root    root       3 Feb 16 15:13 serial.old
-rw-r--r-- 1 root    root    1734 Feb 16 15:12 server.cnf
-rw-r--r-- 1 root    root    4889 Feb 16 15:13 server.crt
-rw-r--r-- 1 root    root    1062 Feb 16 15:13 server.csr
-rw-r--r-- 1 root    root    1854 Feb 16 15:13 server.key
-rw-r--r-- 1 root    root    2835 Feb 16 15:13 server.p12
-rw-r--r-- 1 root    freerad 3854 Feb 16 15:13 server.pem
-rw-r--r-- 1 root    root    2787 Feb 16 15:13 user@example.org.p12
-rw-r--r-- 1 root    root    3794 Feb 16 15:13 user@example.org.pem
-rw-r--r-- 1 root    root    3046 Feb 16 15:12 xpextensions
freerad@ubu:~$ ls /etc/raddb/clients.conf -al
ERROR: ld.so: object '/usr/lib64/libpython3.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
-rw-r----- 1 root freerad 8323 Feb 16 15:12 /etc/raddb/clients.conf
```

### I expected the following

That the RADIUS server starts.

### Kanidm version (and git commit)

36f1efa55996a5deb97821e1a4cdf53bd8112321

### Operating System / Version

```console
ca@ubu:~/kanidm$ uname -a
Linux ubu 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Any other comments

Looks like 5573ab92240342c3e64646e58e7982e55799111a introduced this when switching base image.
It works fine in prior commit, where owner of files was the dedicated RADIUS user.

**Comment by yaleman** [comment]
Curious, I thought I'd fixed that particular set of fail. Thanks, will have a look.
