### ISSUE TITLE
kanidmd crashes on unreachable code at server/lib/src/repl/entry.rs:178

### ISSUE THREAD

**Issue by johanfleury** [kanidm/kanidm#2505]
Hi

I’m running kanidm 1.1.0-rc.16 (`kanidm/server:1.1.0-rc.16`) in Kubernetes. On startup kanidm crashes with the following log:

```
Log filter: Info
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /data has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running in server mode ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting kanidm with configuration: address: [::]:8443, domain: auth.br0.fr, ldap address: disabled, origin: https://auth.br0.fr admin bind path: /data/kanidmd.sock, thread count: 4, dbpath: /data/kanidm.db, arcsize: AUTO, max request size: 262144b, trust X-Forwarded-For: false, with TLS: true, online_backup: disabled, integration mode: false, console output format: Text log_level: inforole: write replica, replication: disabled, otel_grpc_url: None
thread 'main' panicked at server/lib/src/repl/entry.rs:178:17:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: kanidmd_lib::repl::entry::EntryChangeState::change_ava
             at ./usr/src/kanidm/server/lib/src/repl/entry.rs:178:17
   4: kanidmd_lib::entry::Entry<kanidmd_lib::entry::EntryInvalid,STATE>::add_ava
             at ./usr/src/kanidm/server/lib/src/entry.rs:3186:9
   5: kanidmd_lib::entry::Entry<kanidmd_lib::entry::EntryInvalid,STATE>::apply_modlist
             at ./usr/src/kanidm/server/lib/src/entry.rs:3312:21
   6: kanidmd_lib::server::modify::<impl kanidmd_lib::server::QueryServerWriteTransaction>::modify_pre_apply::{{closure}}
             at ./usr/src/kanidm/server/lib/src/server/modify.rs:108:13
   7: core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2521:26
   8: core::iter::traits::iterator::Iterator::try_fold
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2462:21
   9: core::iter::traits::iterator::Iterator::try_for_each
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2524:9
  10: kanidmd_lib::server::modify::<impl kanidmd_lib::server::QueryServerWriteTransaction>::modify_pre_apply
             at ./usr/src/kanidm/server/lib/src/server/modify.rs:107:31
  11: kanidmd_lib::server::modify::<impl kanidmd_lib::server::QueryServerWriteTransaction>::modify
             at ./usr/src/kanidm/server/lib/src/server/modify.rs:15:18
  12: kanidmd_lib::server::modify::<impl kanidmd_lib::server::QueryServerWriteTransaction>::internal_modify
             at ./usr/src/kanidm/server/lib/src/server/modify.rs:433:9
  13: kanidmd_lib::server::migrations::<impl kanidmd_lib::server::QueryServerWriteTransaction>::internal_migrate_or_create
             at ./usr/src/kanidm/server/lib/src/server/migrations.rs:268:21
  14: kanidmd_lib::server::migrations::<impl kanidmd_lib::server::QueryServerWriteTransaction>::initialise_idm::{{closure}}
             at ./usr/src/kanidm/server/lib/src/server/migrations.rs:1039:33
  15: core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2521:26
  16: core::iter::traits::iterator::Iterator::try_fold
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2462:21
  17: core::iter::traits::iterator::Iterator::try_for_each
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/iter/traits/iterator.rs:2524:9
  18: kanidmd_lib::server::migrations::<impl kanidmd_lib::server::QueryServerWriteTransaction>::initialise_idm
             at ./usr/src/kanidm/server/lib/src/server/migrations.rs:1039:14
  19: kanidmd_lib::server::migrations::<impl kanidmd_lib::server::QueryServer>::initialise_helper::{{closure}}::{{closure}}
             at ./usr/src/kanidm/server/lib/src/server/migrations.rs:116:17
  20: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  21: kanidmd_lib::server::migrations::<impl kanidmd_lib::server::QueryServer>::initialise_helper::{{closure}}
             at ./usr/src/kanidm/server/lib/src/server/migrations.rs:10:5
  22: kanidmd_core::setup_qs_idms::{{closure}}
             at ./usr/src/kanidm/server/core/src/lib.rs:111:45
  23: kanidmd_core::create_server_core::{{closure}}
             at ./usr/src/kanidm/server/core/src/lib.rs:842:50
  24: kanidmd::kanidm_main::{{closure}}
             at ./usr/src/kanidm/server/daemon/src/main.rs:539:64
  25: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:63
  26: tokio::runtime::coop::with_budget
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  27: tokio::runtime::coop::budget
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  28: tokio::runtime::park::CachedParkThread::block_on
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:31
  29: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/blocking.rs:66:9
  30: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  31: tokio::runtime::context::runtime::enter_runtime
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  32: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  33: tokio::runtime::runtime::Runtime::block_on
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/runtime.rs:350:50
  34: kanidmd::main
             at ./usr/src/kanidm/server/daemon/src/main.rs:247:5
  35: core::ops::function::FnOnce::call_once
             at ./home/abuild/rpmbuild/BUILD/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Followed by some initialization logs:

```
53cbbb72-e88a-44fc-8cac-188124eafc6d INFO     system_initialisation [ 671ms | 3.15% / 100.00% ]
53cbbb72-e88a-44fc-8cac-188124eafc6d INFO     ┝━ upgrade_reindex [ 301µs | 0.04% ]
53cbbb72-e88a-44fc-8cac-188124eafc6d INFO     ┝━ initialise_schema_core [ 32.1ms | 4.79% ]
```

There are some error in those logs, but I don’t think they are related:

```
53cbbb72-e88a-44fc-8cac-188124eafc6d ERROR    │  ┝━ 🚨 [error]: Failed to convert 'devicekeys' to attribute: InvalidAttributeName("devicekeys") | event_tag_id: 1
```

I can provide the full logs (and full bracktrace) if needed.

One thing worth mentioning is that I deleted the anonymous account, I’m not sure if that’s related.

**Comment by Firstyear** [comment]
You don't need to delete anonymous (you can just expire it, and then it can't authenticate).

I suspect that the delete of anonymous is possibly part of the issue here because the unreachable code you have hit is related to modification of a deleted entry which should be impossible. I will reproduce and harden this to help prevent encountering this situation.

**Comment by johanfleury** [comment]
Is there a way I can restore the user? Maybe some sql queries I could run?

**Comment by Firstyear** [comment]
> Is there a way I can restore the user? Maybe some sql queries I could run?

First shutdown your server. 

Then run `kanidmd db-scan list-index idx_eq_uuid | grep '00000000-0000-0000-0000-ffffffffffff'`

You should see output like:

```
              00000000-0000-0000-0000-ffffffffffff: IDLBitRange (sparse values) 1 (data) [ 161, ]
```

Take the value in the brackets (in this case 161, your value may be different).

Then run:

```
kanidmd db-scan get-id2entry 161
```

Confirm the entry is in state tombstone and class:tombstone is present.

Once you have confirmed this, then run:

```
kanidmd db-scan quarantine-id2entry 161 
```

Confirm the entry is quarantined:

```
kanidmd db-scan list-quarantined
```

Start the server. The migrations should now apply. The anonymous account will be recreated. You should disable it with https://kanidm.github.io/kanidm/stable/accounts/people.html#account-validity

**Comment by johanfleury** [comment]
Awesome, that worked like a charm :)

I’ll let you decide what to do with this issue.

**Comment by Firstyear** [comment]
Going to keep it open so that we merge some improved anonymous account protections so other people don't hit the same issue :)

**Comment by KittyKatt** [comment]
I'm not usually one to necro threads, but I wanted to ask: @johanfleury You have a working version of Kanidm in Kubernetes? Would you mind sharing your manifests? I'm attempting to get this going in my cluster and that would help give me a huge head start.

**Comment by yaleman** [comment]
@KittyKatt I've started a discussion here https://github.com/kanidm/kanidm/discussions/2810 with a link to my manifests etc, let's move there please 😄
